export enum Context {
    GOOGLE_DOC = "GOOGLE-DOC",
    GOOGLE_SHEET = "GOOGLE-SHEET",
    GOOGLE_MEET = "GOOGLE-MEET",
    GOOGLE_CALENDAR = "GOOGLE-CALENDAR",
    GOOGLE_DRIVE = "GOOGLE-DRIVE",
  
    TODOIST_TASK = "TODOIST-TASK",
    LINEAR_TASK = "LINEAR-TASK",
    GITHUB_REPO = "GITHUB-REPO",
    GITHUB_ISSUE = "GITHUB-ISSUE",
    GITHUB_PULL_REQUEST = "GITHUB-PULL-REQUEST",
  
    VERCEL = "VERCEL",
    HEROKU = "HEROKU",
    NETLIFY = "NETLIFY",
  
    MICROSOFT_WORD_DOC = "MICROSOFT-WORD-DOC",
    MICROSOFT_EXCEL_DOC = "MICROSOFT-EXCEL-DOC",
    MICROSOFT_TEAMS_MEET = "MICROSOFT-TEAMS-MEET",
    MICROSOFT_OUTLOOK_CALENDAR = "MICROSOFT-OUTLOOK-CALENDAR",
    MICROSOFT_ONEDRIVE_DRIVE = "MICROSOFT-ONEDRIVE-DRIVE",
  
    EMAIL = "EMAIL",
  
    TWITTER_DATA = "TWITTER-DATA",
  
    DISCORD = "DISCORD",
    WHATSAPP = "WHATSAPP",
    TELEGRAM = "TELEGRAM",
    LINKEDIN = "LINKEDIN",
    SLACK = "SLACK",
    INSTAGRAM = "INSTAGRAM",
  }
  
  



  